### ISSUE TITLE
Move packages to "games" subdirectory?

### ISSUE THREAD

**Issue by jedahan** [sdsddsd1/kiss-games#15]
I had some trouble setting up KISS_PATH because I thought the kiss community repository was just under `community` but actually has all the packages in a subdirectory `community/community`. I asked @dylanaraps about it, and said it wasn't going to change with some good reasoning behind it. For consistencies sake, would you accept a PR moving all the packages to a subdirectory, with an update to the readme? For what its worth, I asked the same of mywayland https://github.com/sdsddsd1/mywayland/issues/1

Dylan's reasons:
* It prevents a mess of directories in the root of the repository
* It allows for things like 'community-testing' to be added if needed in the future.
* It's identical to how the official repositories in its layout

**Comment by sdsddsd1** [comment]
I appreciate your efforts but I wont change the directory structure. I am not planning to add additional subrepos to kiss-games or mywayland. There would be just a useless directory you  have to move through when doing stuff. I think of this when the repos would actually need it.
