### ISSUE TITLE
mgba build fails

### ISSUE THREAD

**Issue by icyphox** [sdsddsd1/kiss-games#22]
Not entirely sure what the issue is here. Here's the `kiss build mgba` log: https://termbin.com/f004

**Comment by sdsddsd1** [comment]
I can confirm. There is https://github.com/mgba-emu/mgba/issues/1656
Ping @eudaldgr . I think I tested mgba and there was no problem.

**Comment by sdsddsd1** [comment]
@icyphox : Ffmpeg was missing as make dependency. Rebuilding xz first and then ffmpeg fixed this issue. See: https://github.com/kisslinux/community/issues/647 . Please test and close if so.

**Comment by icyphox** [comment]
Yep! That seems to have fixed it, thanks. Closing now.

**Comment by eudaldgr** [comment]
Oh well, i see now. Too late.
