### ISSUE TITLE
Cave story is actually NX Engine

### ISSUE THREAD

**Issue by deralmas** [sdsddsd1/kiss-games#29]
The "cavestory" package is actually NX Engine, a clone of the Cave Story engine, with many inaccuracies to the original game. It could be both renamed to "nxengine" and replaced with "Cave Story engine 2"(CSE2), which, despite its name, it's actually a port of the decompiled code of Cave Story(which linux port was even compiled with debug info!) to a variety of backends and ensures maximum faithfullness to the original game.

**Comment by sdsddsd1** [comment]
I appreciate your attention for this detail!
I rename the actual package to `nxengine-evo` for repology parsing and update the readme to
`Cave Story (NXEngine-evo)` as reference for the naming disparity.
