### ISSUE TITLE
Minecraft/MultiMC: does it make sense in this repository?

### ISSUE THREAD

**Issue by deralmas** [sdsddsd1/kiss-games#32]
I noticed here the lack of MultiMC, a very famous open source Minecraft client, and i thought that it would make a nice addition, but there are some things stopping me for making a pr:
- Libre issues/Paywall: It still requires a paid minecraft account, and will download closed source executables, is this against this repo's philosophy/objective?
- Dependencies issues: Could be there issues with some of the dependencies? MultiMC requires Java, and all of the Java repos are still pretty in development, but it should have some precompiled binaries available for running the game.

**Comment by sdsddsd1** [comment]
I cant give you any assistance in packaging or running java related programs. 
Non libre content is no problem for me.  
`For me this repo is something to show whats possible on KISS related to gaming`.
There is sauerbraten with nonfree assets afaik and urbanterror I think too.
What ever you get running and want to add will find its place on this repo!
You can also open an issue and document your packaging problems to gain help from the community which visits this repo.

**Comment by deralmas** [comment]
Yeah, but it's also paywalled content, you gotta pay for a minecraft account before being able of playing the game.

**Comment by sdsddsd1** [comment]
Non-free licensing is no problem here!
