### ISSUE TITLE
godot: pip invoked in build

### ISSUE THREAD

**Issue by sdsddsd1** [sdsddsd1/kiss-games#33]
`Scons` is needed to build the package godot. Scons has an awful [dependency trail](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/scons) to build but luckily its installable through `pip`!
A prefix definition through pip is possible but has a bug for scons. Read [here](https://github.com/FPGAwars/apio/issues/144) .
`pip install --install-option="--prefix=$PREFIX_PATH" package_name` does not work. So the build like autoconf or nasm in [firefox](https://github.com/kisslinux/repo/blob/master/extra/firefox/build#L19) cant be adopted by now. :\/
As long as no better solution is found pip is invoked as is. However the package can be forked on user discretion to avoid repeated installation.  Thanks for putting attention on this.
Pullrequests welcome!

**Comment by deralmas** [comment]
Trying to run `pip install --install-option="--prefix=$PREFIX_PATH" package_name` doesn't work, but it also gives me a deprecation warning which says this:
> DEPRECATION: Location-changing options found in --install-option: ['--prefix'] from command line. This configuration may cause unexpected behavior and is unsupported. pip 20.2 will remove support for this functionality. A possible replacement is using pip-level options like --user, --prefix, --root, and --target. You can find discussion regarding this at https://github.com/pypa/pip/issues/7309.

Following the suggestion from the aforementioned message, i tried running `pip install --prefix="$PREFIX_PATH" package_name` and it worked fine.
Am I missing something?

**Comment by sdsddsd1** [comment]
Somehow my pip stoped working while messing around and I was not yet able to fix it, by reinstalling python.
However your suggestion made some progress and I was testing with the following.
Replace the exsting `pip install scons` with
```
(
    pip --disable-pip-version-check --prefix="$PWD/../junk" install scons
)
export PATH="$PDW/junk/bin/:$PATH"
```
Another possibility would be to adopt the build of [webkit2gtk](https://github.com/kisslinux/community/blob/master/community/webkit2gtk/build) which is modifying its build by invoking `kiss s` and change flags accordingly.  
Maybe something similar is possible with pip.

**Comment by sdsddsd1** [comment]
I am not able to fix this at the moment. However there is a note in the post-install.  
When you have working fix feel free to issue again or open a pullrequest.
