### ISSUE TITLE
Split packages - Mark packages with non-free content

### ISSUE THREAD

**Issue by Muvkina** [sdsddsd1/kiss-games#35]
I would like to propose something for the repo however before I start I would like to say obviously this is the maintainers choice just something I would like to see. I would like to see all games that have non free parts of them in one directory labeled something along the lines of nonfree and one labeled libre. I enjoy this repo however I have to go check to make sure every game is completely oss if I choose to download it.

**Comment by sdsddsd1** [comment]
I think this can be something use- and valueable for this repo. I think also the calrity of the `README` is pretty good an straight forward at the moment. Also it is simple and straight forward to have just everything in `one directory` for me to maintain and also for the user who is looking through.  
  
So as you see I am open to this but we have to find a solution which does not mess up with the beforehand mentioned qualities.

**Comment by Muvkina** [comment]
Perhaps label packages accordingly? Perhaps have all packages that are foss just their name and any that have nonfree components -nonfree. Another solution could be a post-install script warning that this program has nonfree parts. One last solution could be is to have a second Document in the main repo named nonfree with a list of all nonfree packages. Just some ideas

**Comment by sdsddsd1** [comment]
I have added a pinned issue, do you have write permissions to it? I think this might me the cleanest solution.
