### ISSUE TITLE
Mednaffe will not open roms due to "Unrecognized argument: -psx.dbg_level"

### ISSUE THREAD

**Issue by josephreynolds1** [sdsddsd1/kiss-games#45]
Mednaffe will not open roms due to "Unrecognized argument: -psx.dbg_level"

![image](https://user-images.githubusercontent.com/46980014/85232883-b8031280-b3d0-11ea-9e7f-162d1d5a0746.png)

**Comment by sdsddsd1** [comment]
I have just tested 8bit and 16bit consoles. Are you trying psx?
Some more infos would be nice. Things I would work through and then searching the  upstream repo and further net:
- Output of terminal and frontend the same?
- Which console?
- Which game? Every game the same?
- Are older versions behaving the same?

Note: It is out of my sight to test every little feature of the games provided here.

**Comment by josephreynolds1** [comment]
This happens when I try to open any game (nes,snes,etc.)

This is also default config except for adding a path to roms and changing the shader video settings to Goat/Borg.

If I run mednafen directly and remove the -psx.dbg_level 0 from the command line it opens the game without issue.

[04:50 PM] user@KISS [~/Games] $ mednaffe 
Starting Mednaffe 0.8.8
Mednafen configuration file found.
Mednafen version detected: 1.24.3
----

Executing mednafen with command line: 
"/usr/bin/mednafen **-psx.dbg_level 0** -ss.shader goat -md.shader goat -psx.region_default na -snes.shader.goat.pat borg -snes.shader goat -pce.shader.goat.pat borg -pce.shader goat -ss.shader.goat.pat borg -nes.shader.goat.pat borg -psx.shader goat -nes.shader goat -md.shader.goat.pat borg -psx.shader.goat.pat borg /home/user/Games/emu/nes/streemerz-v02.nes "

**Comment by sdsddsd1** [comment]
I think the [mednaffe github](https://github.com/AmatCoder/mednaffe/issues) is a better place for this, as it seems to to be a problem with the software itself than the package.
Another thing: Could you test to build mednaffe with gtk+3? Then we could avoid the gtk+2 dependency.
```
./configure \
    --prefix=/usr \
    --enable-gtk3

make
make DESTDIR="$1" install
```

**Comment by sdsddsd1** [comment]
I have reproduced your problem. Though I can  not find a solution. I will drop mednaffe since the actual emulator works fine.
Thanks for pointing at.
