### ISSUE TITLE
Help wanted with packaging MAME

### ISSUE THREAD

**Issue by ghost** [sdsddsd1/kiss-games#47]
I'm currently getting these compile errors when I run make:
```
../../../../../3rdparty/bx/src/crtnone.cpp:15:10: fatal error: crt0.h: No such file or directory
   15 | #include "crt0.h"
      |          ^~~~~~~~
compilation terminated.
../../../../../3rdparty/bx/src/debug.cpp:13:11: fatal error: crt0.h: No such file or directory
   13 | # include "crt0.h"
```

It seems like crt0.h is a local header which isn't in the sources. I can't find anyone who has complained about this, so it's probably something on my end? 

I've been at this for a while now, I'm gonna take a break. I hope to leave this thread open for discussion until we can get it packaged.

**Comment by sdsddsd1** [comment]
Can you publish your package efforts? (Sources, build files, dependencies..)

**Comment by sdsddsd1** [comment]
At a first glance, I have found this wiki [article](https://en.wikipedia.org/wiki/Crt0) . As far as I understand this is something our C library has to do with. 

Edit: Searching for `crt0.h not found` I have found this [issue](https://github.com/bkaradzic/bx/issues/242) about your provided error message on a musl system.  
The link they provide mentions what alpine does in their [patch](https://git.alpinelinux.org/aports/tree/testing/mame/fix-musl.patch) for mame.

**Comment by sdsddsd1** [comment]
@IslandAlpha : feel free to reopen this issue if requiered.
