### ISSUE TITLE
solvitaire: checksum mismatch

### ISSUE THREAD

**Issue by ghost** [sdsddsd1/kiss-games#5]
What I generated:
`894bb6bd4c1a7bfb1275ed6854d61d487d85f7dea54cbe9a3c6fba21976b14c7  master.tar.gz`

In `checksums`:
`af892e9fb92b5e89179b7dc09e95eeb20092ec28d784089b60c749399dd04abe  master.tar.gz`

**Comment by sdsddsd1** [comment]
This package has no release as source so there cant be a real checksum. Fixed. Thanks for your attention!
