### ISSUE TITLE
Retroarch: missing dependency

### ISSUE THREAD

**Issue by sdsddsd1** [sdsddsd1/kiss-games#53]
@eudaldgr 
I went to `kiss-games/libretro` and did a `kiss b *`. There are two missing deps:  
libretro-desume - `libpcap`
libretro-mupen64plus - `nasm`.

What do you think about a small instruction how to install RetroArch(which package for a base) and where to put roms/ bios etc?
If you like I can write a text about key notes you give.

**Comment by sdsddsd1** [comment]
When the [libusb](https://github.com/kisslinux/community/issues/1105) build is changed, we can avoid the eudev dependency for `retroarch`, or enable it conditionally like it is done in `libinput`.

**Comment by eudaldgr** [comment]
I added some changes to the packages to only need `retroarch` to install a base minimum without cores, next thing is to write how to add roms/bios... but this need to be done another day, now i have no time. I accept help with this.

**Comment by sdsddsd1** [comment]
This looks good at a first glance. I will try to spend some time with retroarch and get familiar with it.
At the moment retroarch does not start with libudev-zero and libusb. I want to add a note about this issue at the readme after more thought. Probably leave eudev enabled in the retroarch build and give advice to fork and disable it. No rush.
