### ISSUE TITLE
retroarch: WIP quickstart guide

### ISSUE THREAD

**Issue by sdsddsd1** [sdsddsd1/kiss-games#57]
This is a follow up from https://github.com/sdsddsd1/kiss-games/issues/53 .
- There is an issue with libudev-zero and libusb. A note and forking advice would ne suiteable in the readme.  
 We could also enable eudev conditionaly, just when udev is installed to avoid it when possible.
- Where is retroarch configured? Point at `$HOME/.config/retroarch/retroarch.cfg`.
- Where to put bios/firmware? Point at `$HOME/.config/retroarch/system`.
- Where to put roms? Roms have no specified path. Can be set in menu.  
- Why is the online updater disabled? (Targeted at glibc).

We have `libretro-database` and I _think_ the path is correct in `retroarch.cfg` but no thumnails are showing up.
Have you success with this? I have just enabled the online updater and pulled the thumbnail stuff that way. Tested with my pc-engine collection.   
Thought: Isnt the online-updater a good solution anyway and should be enabled? Also one package less.

This and what you have already written should be enough to get one started I _think_. At least from the KISS  
side of things. Maybe a nice guide can be found for a general setup to not reinvent the wheel.

**Comment by eudaldgr** [comment]
Online-updater is disabled, because they will download, create and modify files without go through the package manager, like `libretro-database` or `retroarch-assets`, and the cores are built for `glibc`.
Thumbnail stuff automatic can be done with some change on the configuration. PR in the way.
The other way is to make a package with all of the [thumbnail](http://thumbnailpacks.libretro.com/) available, only GBA is about ~350MB

**Comment by sdsddsd1** [comment]
I see. Autodownload of thumbnails now works. I think thats pretty good now.  
Edit: I think a rationale about the disabled updater should have a note in the readme.

**Comment by sdsddsd1** [comment]
I put the above list in some text.  I would also like to remove the list of cores from the readme as they are quite redundant to the list of packages above. 

The emulators, so called 'cores', start with `libretro-` followed by the
corresponding name. Once installed, retroarch will pick them up.
The online updater is disabled as retroarch's buildsystem is targeted at glibc
and therefore the whole suite is managed by the package manager. Only preview
thumbnails are downloaded once at runtime.
Configuration is done at `$HOME/.config/retroarch/retroarch.cfg` and additional
firmware goes in `$HOME/.config/retroarch/system/`.
Roms have no specified path and can live anywhere on the system. They are added
inside retroarch. 'Import content -> Scan directory'.

**Comment by sdsddsd1** [comment]
From my side, the quick start guide looks good and I think it is finished. I still have to play with udev/libudev zero but I think libudev-zero works now in its current state. For me this issue is done and I would open a new one for the udev thing then.

**Comment by eudaldgr** [comment]
I agree with that, respect `libudev-zero` i still don't know how it works and what it do and what don't.

**Comment by sdsddsd1** [comment]
Its a drop in repalcement. It mimics to look like udev (wlroots, other stuff wich harddepends on udev), but works without a deamon and lets you choose other device manager.

**Comment by sdsddsd1** [comment]
Re libudev-zero: At the moment 'udev' or 'libudev-zero' is required by KISS. So we can leave retroarch as it is.
@eudaldgr
