### ISSUE TITLE
Midi music in doomretro does not work

### ISSUE THREAD

**Issue by josephreynolds1** [sdsddsd1/kiss-games#73]
With a clean install of doomretro I get the following error in the ingame console.

The *musicfilename* music lump cannot be played.

doomretro works fine when run on debian with the same wad files (doom1,doom2,etc.)

doomretro 3.6.1 1
fluidsynth 2.1.4 1
sdl2 2.0.12 1
sdl2-image 2.0.5 1
sdl2-mixer 2.0.4 1
soundfont-fluid 3.1 1

**Comment by sdsddsd1** [comment]
Have a look at: https://github.com/sdsddsd1/kiss-games/blob/master/equipment/fluidsynth/build#L16 and https://github.com/sdsddsd1/kiss-games/blob/master/equipment/soundfont-fluid/build . 
You need to tell fluidsynth which soundfont to choose. You could even install a different sound soundfont.

**Comment by sdsddsd1** [comment]
Reopen if you need.
