### ISSUE TITLE
Vinox

### ISSUE THREAD

**Issue by Muvkina** [sdsddsd1/kiss-games#76]
I'm not sure if you keep game engines/frameworks as well. However I am working on a game library that focuses  on KISS and think it may be a good fit here if you do have game engines/frameworks. 

If you'd like to see what I have so far to help give you a idea https//github.com/muevoid/vinox

**Comment by sdsddsd1** [comment]
To quote the README "If you want to see your beloved gem on this repo, submit a package". (: I think this is really cool. We could add this to 'Emulator, engine' . If you like submit a PR.
Edit: You were asking about exmaples on IRC: what about the chromium dino runner?

**Comment by Muvkina** [comment]
Can do on sumbitting a pr and that's a great idea! I will work on that later today. I will close this issue and sumbit a pr later today.
