### ISSUE TITLE
New list about wayland compatability

### ISSUE THREAD

**Issue by Muvkina** [sdsddsd1/kiss-games#79]
I think it also may be beneficial to have another list like the non free list except for games that work withoout libX11 on wayland. What are your thoughts?

**Comment by sdsddsd1** [comment]
Sure! I have thought about this too, but I had not have yet the motivation to sort this out. As mentioned my machine is currently broken. Altough I run wayland on this my setup is with all the xorg stuff because of _this_ repo for combatibilty.
If you like we can collect on this thread and setup a tidy other one or also include this in the readme.
edit: Some things might be sorted out before. Some things requiere  e.g ´libgl´ which can be provided by mesa (libX11) or libglvnd(without libX11). Some games (Xonotic) might requiere libX11 in general.

**Comment by Muvkina** [comment]
Anything works for me readme or another list. I know for sure crispy doom, VVVVV, powdertoy, and nxengine-evo work. Obvi terminal games work too. I can slowly start to test more and more games.

Some things that dont work for sure are any sdl games and irrlicht games

**Comment by sdsddsd1** [comment]
What is your wayland setup at the moment, I assume wayland only without any xorglibs?

On Gh we can use this nice markdown with checkboxes etc. This might be good for a overview and also add oppotunity for comment.
```
Racing:
- [ ] Extreme Tux Racer
- [x] SRB2Kart
- [x] SuperTuxKart

Doom:
- [x] Crispy Doom
- [x] Doom Retro
- [ ] GZDoom
- [ ] PrBoom+

FPS:
- [ ] AssaultCube
- [ ] BetterSpades
- [ ] Nblood
- [ ] OpenArena - Not working (sdl1)
- [ ] QuakeSpasm
- [ ] Redeclipse
- [ ] Sauerbraten - Not working (sdl1)
- [ ] Urban Terror - Not working (sdl1)
- [x] Xonotic - requieres libX11
- [ ] Yamagi Quake 2
- [ ] ZGloom

Shoot'em *:
- [ ] Astromenace
- [ ] C-Dogs
- [ ] OpenTyrian
- [ ] Taisei

Emulator:
- [ ] Godot
- [ ] Irrlicht
- [ ] LÖVE
- [ ] Mednafen
- [ ] mGBA
- [ ] Retroarch
- [ ] Solarus
- [ ] Stockfish
- [ ] Vinox

Roguelike:
- [ ] Brogue CE
- [ ] Cataclysm-DDA
- [ ] Flare
- [ ]HyperRogue

Strategic:
- [ ] Endless Sky
- [ ] OpenTTD
- [ ] Warzone 2100
- [ ] Wesnoth

Jump'n *
- [x] NXEngine
- [ ] Dave Gnukem
- [ ] Hurrican
- [ ] Jazz JackRabbit
- [ ] SDLPoP
- [x] SRB2
- [ ] Teeworlds
- [x] VVVVV
- [ ] watercloset

Other:
- [ ] Ace of Penguins
- [ ] Blobby Volley2 
- [ ] Block Attack
- [ ] dopewars
- [ ] Mr. Boom
- [ ] Neverball
- [ ] oshu!
- [ ] Pingus
- [ ] Xmahjongg
- [ ] Zatacka X

Sandbox:
- [ ] Minetest
- [ ] The Powder Toy
```

**Comment by Muvkina** [comment]
That looks very nice I like that idea. And yes my setup is pure wayland absolutely no xlibs not even libglvnd.

However I may be installing libglvnd have not tried it

**Comment by sdsddsd1** [comment]
Are you working on this list? Otherwise I would close the issue for now.

**Comment by Muvkina** [comment]
I forgot that I had this issue opened my bad. I can name off some. the powder toy, vinox, and c-dogs. I have been working on projects lately so I will close this for now but if I come back to this I will reopen it. Sorry for the trouble.

**Comment by sdsddsd1** [comment]
No worries.
