### ISSUE TITLE
Migration to Wayland

### ISSUE THREAD

**Issue by sdsddsd1** [sdsddsd1/kiss-games#86]
If KISS goes Wayland, we go too! 
One guidestone of this repo is to extend KISS Linux with games and show what is possible. Packages which do not work in future configurations will be purged.
See https://github.com/kisslinux/repo/issues/270

The future mesa of KISS does not provide `libGL` or `libGLX`. However this graphic API´s are required by many games of this repo.
We could provide support through `libglvnd` which also pulls in libX11 and prob a few others. This would prob satisfy glew/glu, butrequires that mesa has to be forked in order to pick libglvnd up. Not something I lean against at the moment.
Sdl1 support in general can be done through sdl12-compat https://github.com/libsdl-org/sdl12-compat.  

Racing
________________________________________________________________________________

- [x] Dust Racing 2D - needs glx -> libglvnd, qt5-wayland
- [x] ~Extreme Tux Racer~ glew/glu sfml -> dropped. Needs xserver.
- [x] Sonic Robo Blast 2 Kart (SRB2Kart)
- [x] SuperTuxKart -> libglvnd

Doom
________________________________________________________________________________

- [x] Crispy Doom
- [x] dhewm3 -> libglvnd
- [x] DOOM Retro
- [x] GZDoom -> libglvnd
- [x] PrBoom+

FPS
________________________________________________________________________________

- [x] Anarch
- [x]  AssaultCube -> sdl12-compat-git, libglvnd
- [x] ~BetterSpades~ -> needs xorg display -> dropped :(
- [x] iortcw
- [x] NBlood (PCExhumed,RedNukem) -> libglvnd
- [x] OpenArena -> libglvnd
- [x]  openhl -> libglvnd
- [x] QuakeSpasm -> libglvnd
- [x] Redeclipse -> xorg-libs, libglvnd
- [x]  Sauerbraten -> libglvnd
- [x] ~Urban Terror~ -> libglvnd, full fledged xorg-libs. But sefaults
- [x] Xonotic -> libglvnd, xorg-libs
- [x] Yamagi Quake 2 -> libglvnd
- [x] ZGloom

Shoot'em *
________________________________________________________________________________

- [x] Astromenace -> libglvnd
- [x] C-Dogs SDL -> libglvnd
- [x]  OpenTyrian - sdl12-compat
- [x] Taisei -> libglvnd

Emulator, engine, editor
________________________________________________________________________________

- [x] ~Eureka~ glew/glu -> needs xserver(fltk)
- [x] ~Godot~ Xserver/Xwayland seems mandatory -> dropped
- [x] ~Irrlicht~ dropped. needs xorg display
- [x] LOVE
- [x] Mednafen
- [x] mGBA -> libglvnd
- [x] RetroArch needs updating and big package
- [x] Solarus
- [x] Stockfish
- [x] Vinox dropped

Rogue-like, RPG
________________________________________________________________________________

- [x] Brogue CE
- [x] Cataclysm-DDA
- [x] DevilutionX
- [x] Flare
- [x] HyperRogue -> sdl12-compat-git, libglvnd

Strategic
________________________________________________________________________________

- [x] ~Endless Sky~ libglvnd -> has problem to initialize glew -> dropped
- [x] LinCity-NG -> libglvnd
- [x] OpenTTD
- [x] ~Warzone 2100~ glew/glu, glx -> libglvnd
- [x] Wesnoth

Jump'n *
________________________________________________________________________________

- [x] Cave Story (NXEngine-evo)
- [x] ~Dave Gnukem~ sdl1, does not build with compat -> drop
- [x] The Legend of Edgar
- [x] Hurrican sdl12-compat-git
- [x] ~Jazz JackRabbit~ sdl1, runs with compat but black screen -> drop
- [x] SDLPoP
- [x] sm64ex -> sm64ex
- [x] Sonic Robo Blast (SRB2)
- [x] Teeworlds -> libglvnd, xorg-libs 
- [x] VVVVVV
- [x] waterCloset

Other stuff
________________________________________________________________________________

- [x] ~Ace of Penguins~ libXpm -> dropped
- [x] Blobby Volley 2
- [x] Block Attack
- [x] ~dopewars~ sdl1
- [x] Mr. Boom
- [x] Neverball - libglvnd 
- [x] oshu!
- [x] ~Pingus~ sdl1 , sdl12-compat-git
- [x] ~sgt-puzzles~ gdkx.h -> drop
- [x] ~Xmahjongg~ libX11
- [x] ~Zatacka X~ sdl1, does not build with compat -> drop

Sandbox
________________________________________________________________________________

- [x] ~Minetest~ dropped. Needs xorg display
- [x] Numpty Physics -> libglvnd. Box2d needs full fledged xorg-libs
- [x] ~The Powder Toy~ does currently not build

Terminalgames
________________________________________________________________________________

- [x] 2048
- [x] Aop
- [x] cNibbles
- [x] CurseofWar
- [x] greed
- [x] nPush
- [x] nSnake
- [x] solVItaire
- [x] terminal-pong
- [x] vitetris

**Comment by dylanaraps** [comment]
This should make the libglvnd situation easier for you: https://github.com/kisslinux/repo/commit/c509e468c00bd0e9331e9f1592f2b3d7e4b81e03 :)

**Comment by sdsddsd1** [comment]
This came out much better then expected! The following packages do not make the transition to a wayland environment:
 - ExtremeTuxRacer -> Needs Xserver display
 - BetterSpades -> Needs Xserver display
 - Godot -> Has no wayland backend yet. Is announced for v4.0
 - Irrlicht, minetest, minetest-game -> need Xserver display
 - Dave Gnukem -> Does not build with sdl12-compat
 - Jazz JackRabbit -> Runs witch sdl12-compat, but only black screen
 - Ace of Penguins -> Needs libXpm and Xserver display
 -  sgt-puzzles -> Needs gtk+3 build with X backend
 - Xmahjongg -> Needs Xserver display
 - Zatacka X -> Does not build with sdl12-compat
 - Endless-Sky -> Unable to initialize glew
 - powdertoy -> Needs a new dep, fftw compiled with gcc fortran
 - UrbanTerror -> Segmentation fault while starting
